plugins {
    id 'com.gradleup.shadow' version '9.3.1'
    id 'application'
    id 'idea'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.14.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.21.0'
    implementation 'software.amazon.awssdk:http-client-spi:2.41.34'
    implementation 'software.amazon.awssdk:apache-client:2.41.34'

    implementation 'software.amazon.awssdk:s3:2.41.34'
    runtimeOnly 'org.slf4j:slf4j-jdk14:2.0.17'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = 'com.procure.thg.cockroachdb.App'
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}